{
 "title": "Sensor Data Metrics",
 "description": "Dashboard to visualize sensor data metrics including hourly averages, daily peaks, and sensor availability",
 "tags": [
  "traffic",
  "sensors",
  "iot"
 ],
 "time": { "from": "2024-07-01T00:00:00.000Z", "to": "2024-07-08T23:59:59.999Z" },
 "panels": [
  {
   "title": "Sensor Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT availability_percentage, 'ID='||device_id FROM \"sensor_availability\" LATEST ON timestamp PARTITION BY device_id ORDER BY timestamp DESC LIMIT 100",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Daily Peak Traffic Volume",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT date, max_hourly_total as value FROM \"daily_max_hourly_volume\"",
     "selectedFormat": 2
    }
   ]
  },
  {
   "title": "Hourly average vehicle count per sensor",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT timestamp, device_id, current_average FROM \"running_hourly_data\" LATEST ON timestamp PARTITION BY device_id, hour"
    }
   ]
  }
 ]
}