services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-graphdb
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test1234
      - NEO4J_dbms_security_allow__csv__import__from__file__urls=true
    volumes:
      - ./data:/var/lib/neo4j/import
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "test1234", "RETURN 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  neo4j-data-loader:
    image: neo4j:latest
    container_name: neo4j-data-loader
    depends_on:
      neo4j:
        condition: service_healthy
    volumes:
      - ./data:/var/lib/neo4j/import
    environment:
      - NEO4J_URI=neo4j://neo4j:7687
    command: /bin/bash /var/lib/neo4j/import/init-neo4j.sh
    restart: "no"

volumes:
  neo4j_data:
